<script src="{{ asset('Front/js/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('Front/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('Front/js/jquery.appear.js') }}"></script>
<script src="{{ asset('Front/js/jquery.easing.min.js') }}"></script>
<script src="{{ asset('Front/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('Front/js/modernizr.custom.13711.js') }}"></script>
<script src="{{ asset('Front/js/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('Front/js/wow.min.js') }}"></script>
<script src="{{ asset('Front/js/progress-bar.min.js') }}"></script>
<script src="{{ asset('Front/js/circle-progress.js') }}"></script>
<script src="{{ asset('Frontjs/isotope.pkgd.min.js/') }}"></script>
<script src="{{ asset('Front/js/imagesloaded.pkgd.min.js') }}"></script>
<script src="{{ asset('Front/js/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('Front/js/count-to.js') }}"></script>
<script src="{{ asset('Front/js/jquery.scrolla.min.js') }}"></script>
<script src="{{ asset('Front/js/YTPlayer.min.js') }}"></script>
<script src="{{ asset('Front/js/TweenMax.min.js') }}"></script>
<script src="{{ asset('Front/js/validnavs.js') }}"></script>
<script src="{{ asset('Front/js/main.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{{-- <script src="{{ asset('Front/js/jquery.floating-social-share.min.js') }}"></script> --}}
<script src="https://cdn.jsdelivr.net/npm/bs5-lightbox@1.8.3/dist/index.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
@stack('script')
